### ISSUE TITLE
Should we move the repo to an organisation?

### ISSUE THREAD

**Issue by bfirsh** [django-ordered-model/django-ordered-model#172]
... now I don’t do much of the maintaining.

Maybe 
https://jazzband.co ? @jezdez - what’s the process for adding a project? The website seems to imply we can just move it if it satisfies the requirements, but is there any additional etiquette I should be aware of?

**Comment by shuckc** [comment]
It doesn't bother me (and this way I don't have to update `requirements.txt` github path :-)

**Comment by imomaliev** [comment]
I think this is great idea, but before that I would like to finish on closing already open PRs and issues, also I wanted to rewrite some internal parts, because they are very outdated. But we could start this process and see if there are some other code quality guidelines this project doesn't meet currently

**Comment by imomaliev** [comment]
@bfirsh Also I would like to discuss our release process.

**Comment by bfirsh** [comment]
@imomaliev indeed - or the lack of one. :)

**Comment by jezdez** [comment]
@bfirsh Yeah, that's basically it. As long as the [guidelines](https://jazzband.co/about/guidelines) are followed you should be good. Plus, you've already followed etiquette and pinged me here :) Once you've transferred the repo it'll automatically open a ticket with a TODO list to make sure all is working well.

In terms of PyPI releases we have an optional new way to do this semi-automatically, where Travis releases things to the Jazzband site and you'll get the chance to review the release before it's pushed to PyPI with a press of a button. [More infos in the docs.](https://jazzband.co/about/releases)

**Comment by jezdez** [comment]
I should note, the people being able to review and confirm the releases can be one or more people that you as the old maintainer choose.

**Comment by shuckc** [comment]
There are compelling reasons to move or create an organisation, especially to aid the management of github action secrets and repository configuration. If we don't particularly want to join Jazzband, we could set up a single purpose github organisation just for this repo. For instance see:

https://github.com/django-money/django-money
https://github.com/django-extensions/django-extensions
https://github.com/django-cms/django-cms

Specifically with the Jazzband setup, after reviewing the docs: 

1. I'm unsure about how active or what the benefits of joining the wider community is, and a
2. I can't see why Jazzband projects push packages to jazzband infrastructure first, followed by a later release to PyPi. It seems this is motivated because any JB member can merge any PR, so they 'gate' the release of actual packages.  
3. On balance I would rather limit merge privileges and use the GH code review tooling rather than having to deal with this.

**Comment by jezdez** [comment]
> There are compelling reasons to move or create an organisation, especially to aid the management of github action secrets and repository configuration. If we don't particularly want to join Jazzband, we could set up a single purpose github organisation just for this repo. For instance see:
> 
> https://github.com/django-money/django-money
> https://github.com/django-extensions/django-extensions
> https://github.com/django-cms/django-cms
> 
> Specifically with the Jazzband setup, after reviewing the docs:
> 
>     1. I'm unsure about how active or what the benefits of joining the wider community is, and a

We're still growing ([879 members as of writing this](https://jazzband.co/members), [53 projects](https://jazzband.co/projects)) and have many proposed projects in the pipeline that we're waiting to onboard at the moment. That said the active community is a fraction of all members though.

>     2. I can't see why Jazzband projects push packages to jazzband infrastructure first, followed by a later release to PyPi. It seems this is motivated because any JB member can merge any PR, so they gate the release of actual packages 'for security'.

There are a few preconditions for this area of Jazzband:

- requesting new PyPI releases is one of the most common requests in long-lived projects
- one strategy to reduce the maintenance burden is automating some of the repeptetive tasks
- another strategy is lowering the barrier to contribute through various means (like giving commit permissions very early)

When trying to cater to all of the above, there are increased risks of abuse of course, especially when members can push Git tags that trigger the release process. So that's why there are project leads to review the releases before they are pushed to PyPI, to make sure the changes in the release are benign.

>     3. On balance I would rather limit merge privileges and use the GH code review tooling as we do currently.

That's a perfectly fine strategy to handle contributions if you have a working pipeline of new contributors. It's the main strategy that GitHub is suggesting projects to follow after all.

**Comment by bfirsh** [comment]
Hello @jezdez. :)

Maybe for simplicity, and to fix the urgent problem of @shuckc needing to be able to add a secret, let's move this to its own org. We can then re-open the discussion about moving it to jazzband.

**Comment by imomaliev** [comment]
@bfirsh I think this is a great middle ground. +1

**Comment by shuckc** [comment]
I’ve sent @bfirsh and @imomaliev invitations to the organisation `django-ordered-model`. Ben has accepted and been made an Admin. To go ahead Ben will need to start the transfer from his personal GitHub account.

**Comment by jezdez** [comment]
> Hello @jezdez. :)
> 
> Maybe for simplicity, and to fix the urgent problem of @shuckc needing to be able to add a secret, let's move this to its own org. We can then re-open the discussion about moving it to jazzband.

Makes sense to me, feel free to open an [issue with a proposal](https://github.com/jazzband-roadies/help/issues/new?assignees=&labels=proposal&template=proposal.md&title=Proposal%3A+%3CPACKAGE+NAME%3E) when you're ready.

**Comment by imomaliev** [comment]
> Makes sense to me, feel free to open an issue with a proposal when you're ready.
Thanks @jezdez

**Comment by bfirsh** [comment]
Done! 🎉
