### ISSUE TITLE
Preserve order while bulk creating through DRF serializers

### ISSUE THREAD

**Issue by onlyphantom** [django-ordered-model/django-ordered-model#252]
Taking code from #251, this is what @ Schwankenson suggested. The key is in the `instance.to(order)` implementation. 

```
from rest_framework import serializers

class OrderedModelSerializer(serializers.ModelSerializer):

    def update(self, instance, validated_data):
        ...
        
    def create(self, validated_data):
        order = None
        if "order" in validated_data:
            order = validated_data.pop("order")

        instance = super().create(validated_data)

        if order is not None:
            instance.to(order)

        return instance
```

How would one suggest I go about doing this in a `bulk_create` fashion? This is a simple skeleton but `order` is not preserved and `instance.to(order)` is also not called, understandably. Any ideas?

```
class OrderedModelSerializer(serializers.ModelSerializer):
      pass

class BulkOrderedModelSerializer(serializers.ModelSerializer):
      orderedmodels = OrderedModelSerializer(many=True)
      class Meta:
          fields = ['orderedmodels']

      def create(self, validated_data):
          create_models = []
          for data in validated_data:
                 create_models.append(OrderedModelSerializer(**data))
          
           return OrderedModel.objects.bulk_create(create_models)
```
Been trying all kind of workarounds, and would appreciate just about any pointers.

**Comment by shuckc** [comment]
Is this essentially the same case we have in https://github.com/django-ordered-model/django-ordered-model/pull/222 ?

**Comment by shuckc** [comment]
As discussed on #222, the default `bulk_create` wont take on the responsibility of applying order values, since it would be slow compared to the usual expectation for `bulks_create` (since we need to do operations over the whole set), and it's not clear how to handle a provided ordering that's inconsistent with the existing items.

Nothing stops you from changing our `OrderedModelQuerySet` behavior to create the objects, then attempting to move them to the desired placement if you are sure your application will be providing consistently ordered objects to `bulk_create`. Something like this might work:

```
# Experiment: try a bulk_create that allows positions to be set rather than
# appending new entries to the end
class BulkItemQuerySet(OrderedModelQuerySet):
    def bulk_create(self, objs, *args, **kwargs):
        order_field_name = self._get_order_field_name()
        desired_order = [getattr(o, order_field_name) for o in objs]
        obs = super().bulk_create(objs, *args, **kwargs)
        for o,i in zip(obs, desired_order):
            o.to(i)

class BulkItemManager(OrderedModelManager):
    def get_queryset(self):
        return BulkItemQuerySet(self.model, using=self._db)

class BulkItem(OrderedModel):
    name = models.CharField(max_length=100)
    objects = BulkItemManager()

```
I'm not sure if this would work with unmodified Serializers or not - I've not used bulk_create from a Serializer before.
