### ISSUE TITLE
Add time complexity information to docs

### ISSUE THREAD

**Issue by mlissner** [django-ordered-model/django-ordered-model#309]
I've been fascinated reading these docs and I've enjoyed thinking about the tradeoffs of the implementation approach vs. performance.

As I'm pondering things, I'm realizing that adding time complexity information for each command in O(n) format would be useful. This is something that the redis documentation does, and it's super handy. 

For example, here's a screenshot:

![image](https://github.com/django-ordered-model/django-ordered-model/assets/236970/2d7eb45d-f70a-427f-977c-9c65fb45c5de)

I'm guessing some of the movement commands are O(n) and others are O(1), and in some cases movement commands are probably interchangeable, so I could see this information being super useful. 

-------

This is somewhat random, but since there's no discussion forum, I thought I'd mention three possible performance optimizations I've been considering. No need to reply if you're busy, but these ideas seemed like possibilities for a performance-oriented fork:

1. It seems like using floats could make this project faster. Rather than moving things around, you could easily slot items between each other.

2. Leaving gaps around could make some things faster. Like, if you move item 2 to position n, you could just leave positions 3..n-1 alone, leaving a gap where 2 was previously. 

3. Using negative numbers and a gap when somebody moves something to the first position, to make the move only take one query even if n is large.

Just some random thoughts. It seems like this project has prioritized readability of the numbers, but if you give that up, you can make things faster — maybe!

**Comment by shuckc** [comment]
For dataset length _n_ I think delete is O(n), insert is O(n) to find the max aggregate (unless db has metadata making it O(1)). Swap are O(1). Reordering is O(n). For a `order_with_respect_to` dataset then reordering is O(n*m) where _m_ is the number of partitions and _n_ the average length. Insert and delete are probably quicker on a partitioned dataset than the same length un-partitioned dataset. A field update on the OWRT fields will be the same cost as insert+delete.

Floats have a finite number of bits, so are not infinitely sub-divisible without eventually becoming equal. So this is no different to using integers with some pre-scaling like *10,000 which is easier to reason about. Eventually a dataset will reach the point where there is no gaps for an insert, and now you have code that runs very rarely trying to resolve the worst case re-ordering, rather than case that runs often and is tested. I don't see what the complexity gets you.

**Comment by mlissner** [comment]
Hi! Back in October you wrote a really helpful comment about performance. I meant to reply just to say thanks, but am noticing that I didn't. Sorry! 

Thanks for the great package and for your thoughtful reply. Great stuff and have a great next nine months!

**Comment by shuckc** [comment]
It feels like most users pop in with roughly the same frequency as the maintainers, so I think we're all good :-)
