### ISSUE TITLE
Ordering with Floats

### ISSUE THREAD

**Issue by robd003** [django-ordered-model/django-ordered-model#322]
It would be really cool if instead of using an integer field to track the order if we could use floating points. This way when moving items significant distances in the order you could just set it to a value between the two adjacent items rather than having to re-order every object between the start and end.

Example:

First obj: 0.129348
Second obj: 0.891234
Third obj: 1.29123042
Fourth obj: 1.8912384

If we wanted to move the First object to after the Fourth object we would just have to set the value greater than `1.8912384` plus some buffer for future moves.

If we used integers we would instead have to change the 'order' field on every single object in the list.

**Comment by urunsiyabend** [comment]
In fact, this problem has been around for a while and many companies use their implementations for user-defined ordering. 

Floating point numbers are not ideal for enumerating large amounts of data due to the precision issue. However, there are already some computational methods that allow adding new elements without reordering the entire table. 

I'm not sure if it's in the context of the django-ordered-model repository, but you can read about the Stern-Brocot Tree for personal research and applications. 

Stern Tree: https://en.m.wikipedia.org/wiki/Stern%E2%80%93Brocot_tree 

Using User Defined Ordering: https://begriffs.com/posts/2018-03-20-user-depth-order.html
