### ISSUE TITLE
Admin move_up_down_links change to Django 1.9 svg

### ISSUE THREAD

**Issue by afk-mario** [django-ordered-model/django-ordered-model#78]
Change the current .gif arrows for the[ new svg used on Django 1.9 admin](https://github.com/django/django/blob/53ccffdb8c8e47a4d4304df453d8c79a9be295ab/django/contrib/admin/static/admin/img/sorting-icons.svg)

**Comment by shuckc** [comment]
The DB round trip to collect max values looks suspect with filtered admin views - which `order_with_respect_to` is the max-item count cached for? I would have expected to see the cache contain both the respect_to and the max-item as a tuple. 

The actual switch to use the built-in icons is just cosmetic, but worth doing at some point. Perhaps rather than have the fancy switching mechanics we should just stop supporting Django < 1.8 and update the urls?

**Comment by shuckc** [comment]
The built in svg icons do not include `move to top`/`move to bottom` icons, so this is no longer possible. Unless we take on the artwork ourselves and improve it.
